<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Seed the products table with realistic Ryoki Skincare products and Shopee store metadata.
     */
    public function run(): void
    {
        $products = [
            [
                'name'           => 'Ryoki Gentle Glow Facial Wash',
                'slug'           => 'ryoki-gentle-glow-facial-wash',
                'description'    => 'RYOKI Facial Wash hadir dengan formula Fish Collagen dari Jepang, Niacinamide, dan Alpha Arbutin untuk membersihkan wajah sekaligus merawat kelembapan serta mencerahkan kulit.',
                'usage'          => 'Basahi wajah dengan air hangat. Tuangkan 1-2 pump ke telapak tangan, busakan, lalu pijat lembut ke seluruh wajah selama 30 detik. Bilas hingga bersih.',
                'ingredients'    => 'Aqua, Glycerin, Cocamidopropyl Betaine, Niacinamide, Centella Asiatica Extract, Ceramide NP, Allantoin, Sodium Hyaluronate, Phenoxyethanol.',
                'price'          => 50000,
                'category'       => 'Cleanser',
                'image'          => 'images/facial-wash.png',
                'rating'         => 5.0,
                'sold_count'     => 500,
                'review_count'   => 120,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Facial-Wash-Japan-Sabun-Cuci-Muka-Double-Cleansing-100ML-i.286791792.22383743914?extraParams=%7B%22display_model_id%22%3A224559273434%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 150,
                'in_stock'       => true,
                'is_best_seller' => true,
                'is_featured'    => true,
            ],
            [
                'name'           => 'Ryoki Gold Whitening Serum',
                'slug'           => 'ryoki-gold-whitening-serum',
                'description'    => 'Serum pencerah wajah dengan konsentrasi Niacinamide 10% dan ekstrak Licorice Root yang bekerja sinergis meratakan warna kulit, menyamarkan noda hitam, dan mengecilkan tampilan pori-pori.',
                'usage'          => 'Setelah toner, teteskan 2-3 tetes pada wajah dan leher. Tepuk-tepuk lembut hingga meresap sempurna. Gunakan setiap pagi dan malam hari.',
                'ingredients'    => 'Aqua, Niacinamide, Butylene Glycol, Glycyrrhiza Glabra (Licorice) Root Extract, Sodium Hyaluronate, Panthenol, Adenosine, Phenoxyethanol.',
                'price'          => 60000,
                'category'       => 'Serum',
                'image'          => 'images/serum.png',
                'rating'         => 4.9,
                'sold_count'     => 2500,
                'review_count'   => 540,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Gold-Whitening-Serum-Japan-Fish-Collagen-15ML-i.286791792.22783859683?extraParams=%7B%22display_model_id%22%3A253995441609%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 120,
                'in_stock'       => true,
                'is_best_seller' => true,
                'is_featured'    => true,
            ],
            [
                'name'           => 'Ryoki Day Cream',
                'slug'           => 'ryoki-day-cream',
                'description'    => 'Pelembap ringan dengan kompleks 5 jenis Ceramide yang mengunci kelembapan hingga 72 jam, memperbaiki skin barrier yang rusak, dan menenangkan kulit kemerahan akibat iritasi.',
                'usage'          => 'Ambil secukupnya, oleskan merata pada wajah dan leher setelah menggunakan serum. digunakan di pagi.',
                'ingredients'    => 'Niacinamide, UV Protection, Hyaluronic Acid, Collagen Extract.',
                'price'          => 75000,
                'category'       => 'Moisturizer',
                'image'          => 'images/day-cream.png',
                'rating'         => 5.0,
                'sold_count'     => 600,
                'review_count'   => 130,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Luminous-Day-Cream-Glowing-Japan-Whitening-Solution-10-gr-i.286791792.23058240243?extraParams=%7B%22display_model_id%22%3A157965715867%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 85,
                'in_stock'       => true,
                'is_best_seller' => false,
                'is_featured'    => true,
            ],
            [
                'name'           => 'Ryoki Night Cream',
                'slug'           => 'ryoki-night-cream',
                'description'    => 'Krim malam intensif dengan Alpha Arbutin 2% dan Collagen yang bekerja selama tidur untuk menyamarkan hiperpigmentasi, memudarkan flek hitam, dan mengembalikan kecerahan alami kulit.',
                'usage'          => 'Oleskan merata pada wajah dan leher sebelum tidur sebagai langkah terakhir. Gunakan setiap malam untuk hasil optimal dalam 4 minggu.',
                'ingredients'    => 'Aqua, Alpha Arbutin, Hydrolyzed Collagen, Niacinamide, Sodium Hyaluronate, Squalane, Tocopheryl Acetate, Phenoxyethanol.',
                'price'          => 96667,
                'category'       => 'Moisturizer',
                'image'          => 'images/night-cream.png',
                'rating'         => 5.0,
                'sold_count'     => 600,
                'review_count'   => 125,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Luminous-Night-Cream-Glowing-Japan-Whitening-Solution-10-gr-i.286791792.23258357874?extraParams=%7B%22display_model_id%22%3A291876891488%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 75,
                'in_stock'       => true,
                'is_best_seller' => false,
                'is_featured'    => true,
            ],
            [
                'name'           => 'Ryoki Face Toner',
                'slug'           => 'ryoki-face-toner',
                'description'    => 'Toner sekaligus essence dengan Hyaluronic Acid berlapis yang menghidrasi kulit secara mendalam dan mempersiapkan kulit untuk menyerap produk skincare selanjutnya secara maksimal.',
                'usage'          => 'Tuangkan secukupnya ke telapak tangan atau kapas. Aplikasikan pada wajah yang sudah dibersihkan dengan gerakan menepuk lembut.',
                'ingredients'    => 'Fish Collagen, Alpha Arbutin, Niacinamide, Aloe Barbadensis Extract.',
                'price'          => 50000,
                'category'       => 'Toner',
                'image'          => 'images/face-toner.png',
                'rating'         => 5.0,
                'sold_count'     => 400,
                'review_count'   => 110,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Toner-Toning-Solution-Exfoliating-Hydrating-100ML-i.286791792.16296432525?extraParams=%7B%22display_model_id%22%3A266877594263%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 95,
                'in_stock'       => true,
                'is_best_seller' => false,
                'is_featured'    => false,
            ],
            [
                'name'           => 'Miss Comby Comby',
                'slug'           => 'miss-comby-comby',
                'description'    => 'Jaga kesehatan dan kenyamanan area intimmu dengan Miss Comby Comb, sabun kewanitaan berbahan dasar ekstrak daun sirih & bahan alami pilihan.',
                'usage'          => 'Kocok botol terlebih dahulu sebelum digunakan, Semprotkan Miss Comb Comb langsung pada area kewanitaan bagian luar dari jarak ±10–15 cm, Diamkan beberapa detik agar formula alami meresap dan memberi rasa segar, Tidak perlu dibilas, cukup biarkan kering dengan sendirinya, Bisa digunakan setiap hari, terutama setelah aktivitas, saat menstruasi, atau sebelum tidur.',
                'ingredients'    => 'Ekstrak Sirih Alami, pH Balanced.',
                'price'          => 65679,
                'category'       => 'Cleanser',
                'image'          => 'images/miss-comby-comby.png',
                'rating'         => 4.9,
                'sold_count'     => 3200,
                'review_count'   => 570,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Miss-Comby-Comby-Feminine-Wash-Sabun-Pembersih-Miss-V-60ML-i.286791792.21194356764?extraParams=%7B%22display_model_id%22%3A266876459976%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 110,
                'in_stock'       => true,
                'is_best_seller' => false,
                'is_featured'    => false,
            ],
            [
                'name'           => 'Ryoki Brightening Peeling Spray',
                'slug'           => 'ryoki-brightening-peeling-spray',
                'description'    => 'Exfoliating spray yang mengangkat sel kulit mati secara instan tanpa perlu digosok kasar. Diperkaya Aloe Vera dan Grape Seed Extract untuk menghaluskan tekstur dan mencerahkan kulit wajah serta tubuh.',
                'usage'          => 'Semprotkan pada area kulit yang kering, diamkan 10 detik, lalu pijat lembut secara melingkar. Bilas dengan air bersih. Gunakan 2-3 kali seminggu.',
                'ingredients'    => 'Aqua, Aloe Barbadensis Leaf Extract, Vitis Vinifera (Grape) Seed Extract, Glycolic Acid, Cellulose, Glycerin, Panthenol, Phenoxyethanol.',
                'price'          => 116667,
                'category'       => 'Cleanser',
                'image'          => 'images/peeling-spray.png',
                'rating'         => 4.9,
                'sold_count'     => 2500,
                'review_count'   => 490,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Peeling-spray-Eksfoliation-Kulit-Pembersih-Kotoran-Peeling-Solution-Glowing-25-ML-i.286791792.14099657653?extraParams=%7B%22display_model_id%22%3A234559108729%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 130,
                'in_stock'       => true,
                'is_best_seller' => true,
                'is_featured'    => true,
            ],
            [
                'name'           => 'Ryoki Deodorant Spray',
                'slug'           => 'ryoki-deodorant-spray',
                'description'    => 'Deodorant spray praktis dengan ekstrak alami yang memberikan kesegaran tahan lama dan menjaga area ketiak tetap kering tanpa rasa lengket.',
                'usage'          => 'Kocok sebelum gunakan. Semprotkan 10-15 cm dari ketiak yang bersih dan kering. Gunakan setiap pagi atau kapan saja diperlukan.',
                'ingredients'    => 'Aqua, Alcohol Denat, Aluminum Chlorohydrate, Aloe Barbadensis Leaf Extract, Fragrance, Glycerin, Phenoxyethanol.',
                'price'          => 43333,
                'category'       => 'Personal Care',
                'image'          => 'images/deodorant-spray.png',
                'rating'         => 5.0,
                'sold_count'     => 900,
                'review_count'   => 205,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Deodorant-Spray-Natural-Japan-Pencerah-ketiak-60ML-i.286791792.28707457864?extraParams=%7B%22display_model_id%22%3A228151164640%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 90,
                'in_stock'       => true,
                'is_best_seller' => false,
                'is_featured'    => false,
            ],
            [
                'name'           => 'Ryoki Hand Body',
                'slug'           => 'ryoki-hand-body',
                'description'    => 'Hand body lotion ringan dengan aroma lembut dan formula pelembap yang menjaga kelembapan kulit tangan dan tubuh sepanjang hari.',
                'usage'          => 'Tuangkan secukupnya pada tangan, lalu usapkan merata ke seluruh tubuh setelah mandi atau kapan saja kulit terasa kering.',
                'ingredients'    => 'Aqua, Glycerin, Shea Butter, Niacinamide, Aloe Barbadensis Leaf Extract, Fragrance, Phenoxyethanol.',
                'price'          => 76667,
                'category'       => 'Body Care',
                'image'          => 'images/hand-body.png',
                'rating'         => 5.0,
                'sold_count'     => 1200,
                'review_count'   => 240,
                'shopee_url'     => 'https://shopee.co.id/RYOKI-Body-Lotion-Whitening-Moisturizing-Alpha-Arbutin-and-niacinamide-100gr-i.286791792.28007462571?extraParams=%7B%22display_model_id%22%3A296876832185%2C%22model_selection_logic%22%3A3%7D',
                'stock'          => 120,
                'in_stock'       => true,
                'is_best_seller' => false,
                'is_featured'    => false,
            ],
            [
                'name'           => 'Ryoki Hair Tonic',
                'slug'           => 'ryoki-hair-tonic',
                'description'    => 'Ryoki Hair Tonic diformulasikan dengan ekstrak Panax Ginseng, Biotin, dan Hydrolyzed Keratin untuk menutrisi akar rambut, mengurangi kerontokan, merangsang pertumbuhan rambut baru, serta memberikan sensasi dingin yang menyegarkan pada kulit kepala.',
                'usage'          => 'Semprotkan Ryoki Hair Tonic secukupnya secara merata pada kulit kepala yang bersih setelah keramas. Pijat lembut kulit kepala selama 2-3 menit dengan ujung jari agar nutrisi meresap sempurna. Gunakan rutin setiap hari tanpa perlu dibilas.',
                'ingredients'    => 'Aqua, Panax Ginseng Root Extract, Aloe Barbadensis Leaf Extract, Biotin, Panthenol, Hydrolyzed Keratin, Menthol, Fragrance, Phenoxyethanol.',
                'price'          => 256667,
                'category'       => 'Hair Care',
                'image'          => 'images/Hair Tonic.png',
                'rating'         => 5.0,
                'sold_count'     => 850,
                'review_count'   => 175,
                'shopee_url'     => 'https://shopee.co.id/ryokiofficialstore',
                'stock'          => 100,
                'in_stock'       => true,
                'is_best_seller' => false,
                'is_featured'    => true,
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
